import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Download } from 'lucide-react';
import { Api, api, errorMessage } from '../services/api';
import { ErrorBox, KV, Loading, Section } from '../components/Common';
import { downloadReport } from '../components/IncidentCard';
import { fmtDate } from '../utils/format';

export default function ReportDetailPage() {
  const { id = '0' } = useParams();
  const q = useQuery({ queryKey: ['report', id], queryFn: () => Api.report(Number(id)) });
  const [blobUrl, setBlobUrl] = useState<string | null>(null);
  useEffect(() => {
    if (!q.data || q.data.status !== 'generated') return;
    let url: string | null = null;
    api.get(`/api/reports/${id}/view`, { responseType: 'blob' }).then((r) => { url = URL.createObjectURL(r.data as Blob); setBlobUrl(url); }).catch(() => setBlobUrl(null));
    return () => { if (url) URL.revokeObjectURL(url); };
  }, [q.data, id]);
  if (q.error) return <ErrorBox error={errorMessage(q.error)} />;
  if (!q.data) return <Loading />;
  const r = q.data;
  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-2"><div><Link to="/reports" className="text-xs text-brand-600 hover:underline">← Reports</Link><h1 className="text-2xl font-extrabold tracking-tight font-mono">{r.file_name}</h1></div><button className="btn-primary" onClick={() => downloadReport(r.id, r.file_name)}><Download size={15} /> Download</button></div>
      <Section title="Report metadata"><KV items={[['Incident', <Link className="font-mono text-brand-700 hover:underline" to={`/incidents/${r.incident_id}`}>{r.incident_id}</Link>], ['Status', r.status], ['Pages', r.pages], ['Size', `${(r.file_size / 1024).toFixed(0)} KB`], ['Generated by', r.generated_by], ['Created', fmtDate(r.created_at)], ['Snapshot', r.snapshot ? `${r.snapshot.classification} · risk ${r.snapshot.risk_score} (${r.snapshot.risk_level}) · ${r.snapshot.human_status} · ${r.snapshot.data_status}` : null]]} /></Section>
      <Section title="PDF preview">{blobUrl ? <iframe title="PDF preview" src={blobUrl} className="w-full h-[80vh] rounded-lg border border-ink-200 dark:border-ink-800 bg-white" /> : <div className="text-sm text-ink-500">Preview unavailable ({r.status}).</div>}</Section>
    </div>
  );
}
